name: Deploy to Production
on: workflow_dispatch

jobs:
  Deploy:
    runs-on: ubuntu-latest
    steps:
      - run: echo "======= MANUAL ========"
      - run: echo "Deproying to production"
      - run: echo "${{ github.event.inputs.tag }}"
      - run: echo "DEPLOYED!"

