name: Deploy to Staging
on: workflow_dispatch

jobs:
  Deploy:
    runs-on: ubuntu-latest
    steps:
      - run: echo "======= MANUAL ========"
      - run: echo "Deproying to staging"
      - run: echo "DEPLOYED!"
